### ISSUE TITLE
Cordova / Ionic

### ISSUE THREAD

**Issue by Munnster83** [EricSmekens/node-bluetooth-obd#17]
Hi Eric,

Do you know if there is anyway to integrate this repo into the cordova / ionic framework for hybrid app development?

http://ionicframework.com/
https://cordova.apache.org/

Thanks in advance,

Chris

**Comment by EricSmekens** [comment]
Good question.
I do not think it is possible. It uses bluetooth-serial-port module, so we need to check if that works for cordova.
