### ISSUE TITLE
Data contains nothing

### ISSUE THREAD

**Issue by Innercode** [EricSmekens/node-bluetooth-obd#20]
Hi,

I've a ELM327 connected to a raspberry. Succesfully paired and trusted.
When I'm running the demo code, data is always empty. Console shows rows with {} What's going wrong?

Thanks in advance!

**Comment by EricSmekens** [comment]
Just retesting this code, and I can partyl verify this issue, for me it keeps saying 'NO DATA'.

**Comment by scramble45** [comment]
::Bump::
I am having the same issue, been using your serial based library that's been working great. Bought a cheap ELM327 BT adapter the code pairs to it automatically. I also had to take out the ATZ and now I get:

````
{ value: 'NO DATA' }
````

Any ideas?
