### ISSUE TITLE
VIN

### ISSUE THREAD

**Issue by scramble45** [EricSmekens/node-bluetooth-obd#23]
I'm not having much luck getting the VIN. I made it a little further by adding this in obd.js

````
else if (valueArray[0] === "49") {
        reply.mode = valueArray[0];
        for (var i = 0; i < PIDS.length; i++) {
			console.log('pid length:', PIDS.name);
            if (PIDS[i].mode == "09") {
                reply.name = PIDS[i].name;
				reply.value = PIDS[i].convertToUseful(hexString);
				console.log('value:', reply.value);
            }
        }
    } 
````

Any suggestions as it stands I do not believe the methods for getting VIN actually work... or am I mistaken?

**Comment by EricSmekens** [comment]
No, VIN was a big question mark for me when I was still active with this. Might want to investigate on how other librabries are doing this.

**Comment by scramble45** [comment]
I have noticed with OBDII, that things like the VIN take a while to request, that and battery voltage. Both of those require more time before you will get something back.

**Comment by EricSmekens** [comment]
Okay, good to know. How long, like a second, or multiple of them?

**Comment by scramble45** [comment]
Around 50-100ms it seems

**Comment by csurf** [comment]
Not all vehicles support VIN requests, mainly the older pre-CAN vehicles I believe.
