### ISSUE TITLE
Node Red

### ISSUE THREAD

**Issue by nakiabrewer** [EricSmekens/node-bluetooth-obd#25]
Hi,

I have been experimenting with this in Node Red trying to utilise it using the Node Red NPM node.
Having little to no luck at all and was wondering have you experimented with this and been able to get it to work?

**Comment by EricSmekens** [comment]
No, I didn't heard of it yet.
Do you know what you are missing?

If you have a repository which implements this NODE-red with a example flow of obd, I could have alook at it.

**Comment by nakiabrewer** [comment]
Hi,

At this point in time I am using the following node in node-red to try and expose your bluetooth-obd NPM package.
https://flows.nodered.org/node/node-red-contrib-npm

I am VERY new to Node and after a little more investigation it appears that the NPM package I am trying to expose will need to be fairly basic fit the required structure.

Again, VERY new to Node and Node-Red and would be happy to take any advice.

**Comment by EricSmekens** [comment]
It looks like you need to create some sort of wrapper around the npm package.

**Comment by nakiabrewer** [comment]
Yep correct.

If you don’t mind I will fork your repository and start it as a new Repo with the required chages to make it a Node Red Node.

Nakia Brewer | WesTrac Pty Ltd | Technology and Solutions Manager | Product Support
T: (02) 4964 5051| M: 0458 713 547 | I: www.westrac.com.au<http://www.westrac.com.au/>
[cid:image001.png@01D159E6.AE805090]<http://www.westrac.com.au/>
THE FIRST CHOICE IN EQUIPMENT SOLUTIONS
ACN 009 342 572 | Our applicable terms and conditions can be found at: WesTrac Terms & Conditions<http://www.westrac.com.au/SiteCollectionDocuments/General%20Conditions%20for%20the%20Sale%20of%20Goods%20and%20Services%20by%20WesTrac%20-%20v5%20-%200914.pdf>

This message including any attached files is confidential and may include proprietary or privileged information. If you are not the intended recipient, you are strictly prohibited from using, reproducing, disclosing or distributing the information contained in this email. If you have received this email in error, please contact WesTrac immediately on +61 8 9377 9444 or by return email. We do not accept liability in connection with computer virus, data corruption, delay, interruption, unauthorised access or unauthorised amendment. We reserve the right to monitor all e-mail communications.

**Comment by EricSmekens** [comment]
Please do that! That's what the repo is still here for. 👍 

Let me know any further results or troubles.

**Comment by nakiabrewer** [comment]
Will do.

I am VERY new to Node so it will be a challenge but I am looking forward to it.

Nakia Brewer | WesTrac Pty Ltd | Technology and Solutions Manager | Product Support
T: (02) 4964 5051| M: 0458 713 547 | I: www.westrac.com.au<http://www.westrac.com.au/>
[cid:image001.png@01D159E6.AE805090]<http://www.westrac.com.au/>
THE FIRST CHOICE IN EQUIPMENT SOLUTIONS
ACN 009 342 572 | Our applicable terms and conditions can be found at: WesTrac Terms & Conditions<http://www.westrac.com.au/SiteCollectionDocuments/General%20Conditions%20for%20the%20Sale%20of%20Goods%20and%20Services%20by%20WesTrac%20-%20v5%20-%200914.pdf>

This message including any attached files is confidential and may include proprietary or privileged information. If you are not the intended recipient, you are strictly prohibited from using, reproducing, disclosing or distributing the information contained in this email. If you have received this email in error, please contact WesTrac immediately on +61 8 9377 9444 or by return email. We do not accept liability in connection with computer virus, data corruption, delay, interruption, unauthorised access or unauthorised amendment. We reserve the right to monitor all e-mail communications.

**Comment by LandoLabrum** [comment]
How do I write multiple polars at the same time? to get for example: {{“name”:”rpm”},{“name”:”vss”}} . Thanks for your time! hmu lando@labruminc.com

**Comment by EricSmekens** [comment]
@LandoLabrum Is this related to Node RED? Otherwise please open a new issue.
