### ISSUE TITLE
Accident Detection

### ISSUE THREAD

**Issue by gaurav-bothra** [EricSmekens/node-bluetooth-obd#29]
Can we Detect Accident Using ELM327 OBD2

**Comment by EricSmekens** [comment]
Not out of the box, with this module.

Only thing you could do, is keep track of speed and check if a sudden drop appears.
But that is out of scope of this module.

I suggest asking a question here:
https://stackoverflow.com/questions/tagged/obd-ii

If you have concrete information we could implement in this library, open a new issue.
