### ISSUE TITLE
Parameters Supported By This Library

### ISSUE THREAD

**Issue by KalpitShah7** [EricSmekens/node-bluetooth-obd#30]
This library supports which parameters (such as rpm, speed) in a car for an obd to get values from?
I have already tested rpm, the speed with ELM327 OBD-II.
I also tried to test the fuel level input, but I got no response using this library. It showed no data!
Please let me know the parameters, soon.
Thanks

**Comment by EricSmekens** [comment]
Parameters are here:
https://github.com/EricSmekens/node-bluetooth-obd/blob/master/lib/obdInfo.js#L267

So it was either not in the list, or the vehicle you queried did not support this.
If you are querying a correct param, and you can get the value out of the vehicle with another tool, please comment & reopen.
