### ISSUE TITLE
Npm install failing

### ISSUE THREAD

**Issue by sundar2323** [EricSmekens/node-bluetooth-obd#8]
Unable to use this for the moment. Please help
Ubuntu 14 is the OS used

Details:
_modules/bluetooth-serial-port/build'
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o
../src/linux/DeviceINQ.cc:35:37: fatal error: bluetooth/bluetooth.h: No such file or directory
     #include <bluetooth/bluetooth.h>
                                     ^
compilation terminated.
make: *** [Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o] Error 1
make: Leaving directory `/home/home/node_sundar/node_modules/bluetooth-obd/node_modules/bluetooth-serial-port/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by EricSmekens** [comment]
This seems to be related with bluetooth-serial-port module. I will test this in +-12 hours when I have time, and if that is the case, I will forward the isse to that module and update mine as soon that one is fixed.

**Comment by EricSmekens** [comment]
@sundar2323 Do you still have this problem?

**Comment by thinhbk** [comment]
Hi @EricSmekens, I get this error when trying to install the package.
OS: 8.1 Enterprise x64, Nodejs: v6.9.1, npm: 3.8.9.

Log:

$ npm install bluetooth-obd --save

> bluetooth-serial-port@2.1.2 install E:\Projects\spikes\obd2\node_modules\bluetooth-serial-port
> node-gyp configure build


ThinhPL@301THINHPL-LT E:\Projects\spikes\obd2\node_modules\bluetooth-serial-port
$ if not defined npm_config_node_gyp (node "C:\Users\ThinhPL\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not fo und. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solu tion". [E:\Projects\spikes\obd2\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not fo und. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solu tion". [E:\Projects\spikes\obd2\node_modules\bluetooth-serial-port\build\BluetoothSerialPortServer.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ThinhPL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\ThinhPL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd E:\Projects\spikes\obd2\node_modules\bluetooth-serial-port
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\ThinhPL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bluetooth-obd" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! bluetooth-serial-port@2.1.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bluetooth-serial-port@2.1.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bluetooth-serial-port package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bluetooth-serial-port
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bluetooth-serial-port
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Projects\spikes\obd2\npm-debug.log

Can you have a look?

**Comment by EricSmekens** [comment]
This is due to requirements of https://github.com/eelcocramer/node-bluetooth-serial-port and/or it dependancies.

I think you need install The Windows SDK version 8.1 and/or visual studio for MSBuild.

**Comment by thinhbk** [comment]
Solved by install VS 2013 Community (as Window SDK 8+ version does not include MSBuild tools). tks.

**Comment by fundasappteam** [comment]
So I am assuming this does not work on a pi?
